# Identification
vit_variant: "tiny"
seed: 42

# Data
train_urls: "data/wds_sample_trajectories/train/platonic-{0000..0003}.tar"
val_urls: "data/wds_sample_trajectories/val/platonic-0000.tar"
batch_size: 2
num_workers: 7

# Training & Masking
base_learning_rate: 1.5e-4
weight_decay: 0.05
start_masking_ratio: 0.75
max_epochs: 2
log_every_n_steps: 5
recon_log_every_n_steps: 10

# Compute
accelerator: "cpu"
devices: 1
strategy: "auto"
