# Data & I/O
train_urls: "data/wds_toy/platonic-0000.tar"
val_urls: "data/wds_toy/platonic-0001.tar"
batch_size: 128
num_workers: 7

# Model
hidden_dim: 512
masking_ratio: 0.75

# Training
learning_rate: 0.00015
max_epochs: 400
recon_log_every_n_steps: 1000

# Compute & Hardware Routing
accelerator: "gpu"
devices: 1
strategy: "auto"
